### PR TITLE
Laura Dietz's 2010 doc on directed factor graphs

### PR DESCRIPTION
**Pull request by brendano**
The URL for Laura's old academic homepage doesn't work, so here's a copy of the PDF to live in the repository.

### CODE REVIEW

**Comment by jluttine** [comment]
Great idea! But do you know about the license of the paper or about permissions to redistribute? That is, is it allowed to distribute the paper via this repo?

**Comment by brendano** [comment]
Good question.  Yes, I got permission from Laura to post it here.

**Comment by jluttine** [comment]
That's great. So apparently Laura owns the copyright and not some publisher, right? It'd be great if the permission from the copyright holders (Laura?) would be somewhere in written format. For instance, as a comment here if that's convenient.

To make things simpler, I'd also like to change the GPL license to MIT, which is more permissive. I need an agreement from Laura for that too. Again, for instance, a comment on this thread would be ok.

I'm not an expert on licenses so if someone has better ideas how to handle all this, I'm open for suggestions. :yum:

**Comment by brendano** [comment]
I think MIT and GPL licenses only apply to code.  Are you talking about code?  (I don't know anything about this codebase.)

Let's only talk about documentation for now.  Laura retains copyright on that document so I'll ask her to comment here approving a copy to be in this repository.

**Comment by laura-dietz** [comment]
It is a tech report -- no publisher has their fingers on it if that's your concern.

Jaakko, you know my stance on licenses. As open as possible. I assume for a document a creative common attribution would be good.

I am switching affiliations (again), I hope to soon have a more permanent web presence at which point I will also put the tech report back online.

**Comment by jluttine** [comment]
Thanks Laura! :+1: 

I'll merge this pull request and at the same time clarify the licenses, some day soon. I think the MIT license works also for the tech report because the license says: "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and *associated documentation files* ...". This tech report falls into that category, I'd say. Thus, it'd keep things simpler if there's just MIT for everything instead of different licenses for different files. Phew, how did this become so complicated.. :smile: Anyway, big thanks to both of you! :yum:

**Comment by jluttine** [comment]
Done. Thanks!

**Pull request merged**
